import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import { Fira_Code } from 'next/font/google';
import { cookies } from 'next/headers';
import { createServerClient } from '@supabase/ssr';
import { SessionProvider } from '@/components/SessionProvider';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';

const firaCode = Fira_Code({ subsets: ['latin'], variable: '--font-fira-code' });
const plusJakarta = Plus_Jakarta_Sans({ subsets: ['latin'], variable: '--font-plus-jakarta' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const cookieStore = await cookies();
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { cookies: cookieStore }
  );

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${plusJakarta.variable} ${firaCode.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <SessionProvider session={session}>{children}</SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
